export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'
export const GET_ACCOUNTS_FAIL = 'GET_ACCOUNTS_FAIL'
export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST'

export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS'
export const GET_FEED_FAIL = 'GET_FEED_FAIL'
export const GET_FEED_REQUEST = 'GET_FEED_REQUEST'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'